FEAT: entity 초기 세팅하고 [#1] 반영했읍니다...
TODAY-IT/today-it-backend pull request #2
Opened 2023-03-04 02:11 UTC by anso33

우당탕탕...
가"감"없는 피드백 부탁드립니다..

[issue]
1. 
onetomany 관계있는 daily_intake_standard랑 user
onetoone 관계인 daily meal이랑 meal nutrition facts에서 
![image](https://user-images.githubusercontent.com/68376744/222870339-eb25b6c6-1b8f-4273-9880-618f7165a0fb.png)

![image](https://user-images.githubusercontent.com/68376744/222870355-3a4af55e-e468-4895-b690-ce4ee708d5bc.png)
이런식으로 에러를 내고 있어영..

2. 
erd에 원래 daily_intake_standard.userId 와 user.id 가 일대일 관계였는데 standard : user -> 1 : N 인 것 같아서 일단 그렇게 작성했어요!
확인 부탁드립니당

2023-03-04 03:17 UTC, kyY00n commented
목표 일일 섭취량과 유저가 다대일이라고 생각한 이유가 뭐예용 😶‍🌫️

2023-03-04 03:20 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime test_time;
p1. 카멜케이스로 일관성 유지하는 거 어땡

2023-03-04 03:21 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyMeal.java
> +  private MealType meal_type;
멋져요!!

2023-03-04 03:22 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailySupplement.java
> +public class DailySupplement {
주석 감삼다 ~ 
이거 리드미에 써두는 거는 어떠심?
주석 대체

2023-03-04 03:22 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailySupplement.java
> +//  @Column(name = "id", nullable = false)
이건 모 지

2023-03-04 03:24 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/disease/Disease.java
> +  private List<UserDisease> userDiseaseList = new ArrayList<>();
오 딱 처음 봤을 땐
질병 객체가 이 질병을 앓고 있는 유저들을 왜 알고 있는지 의문쓰
왜 추가했는지 궁금쓰

2023-03-04 03:26 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/mealinfo/MealNutritionFacts.java
> +  private double cholesterol;
p5. 하나로 관리하면 좋을 것 같기도합니당
jpa 에 활용하기 좋은 기능이 있었던것 같은. ..
https://www.baeldung.com/jpa-embedded-embeddable

2023-03-04 03:27 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/standard/DailyIntakeStandard.java
> +  private double cholesterol;
p5. (이어서) 근데 별로면 말구 ><

2023-03-04 03:31 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/user/userinfo/UserSupplement.java
> +public class UserSupplement {
p3. 얘도 nutrients 처럼 standard 붙이는 거는 어떤가유
저는 유저가 섭취한 기록과 헷갈리는 것 같기도 해용

2023-03-04 03:33 UTC, kyY00n commented on todayit/src/main/java/com/juju/todayit/domain/user/userinfo/UserSupplement.java
> +public class UserSupplement {
아니면 밑에 타겟이라는 용어를 쓰니까 그것도 좋을거같아용

2023-03-04 03:37 UTC, kyY00n requested changes
Good 고생많았어!!!!! 
좀좀따리 수정할 수 있는 것들 코멘트 달았어! (이미 다 아는 내용이겠지만)
확인 먼저 하고, 고칠 수 있는지 얘기해줘! (시간 부족하면 내가 해볼게)

2023-03-04 16:18 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime test_time;
반영완!

2023-03-04 22:01 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailySupplement.java
> +public class DailySupplement {
반영완!

2023-03-04 22:03 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailySupplement.java
> +//  @Column(name = "id", nullable = false)
이것 저것 해보던 흔적입니다..ㅋㅎ 지울게염!

2023-03-04 22:12 UTC, anso33 commented
> 목표 일일 섭취량과 유저가 다대일이라고 생각한 이유가 뭐예용 😶‍🌫️

이거슨 섭취량의 케이스로 생각하면 여성, 남성, 여성 당뇨 환자 등등 이렇게 케이스별로 목표 일일 섭취량을 두고 같은 케이스를 가진 유저가 여럿 있을 수 있다고 생각해서 그랬는데 
지금 떠오르는게 ERD 짤 때 내용이 중복되어도 걍 유저별로 각자 목료 일일 섭취량을 설정할 수 있도록 하자고 했던 기억이 나는것도 같네요!?!??ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하핫 그렇다면 일대일이 맞는것도 같습니당...  우리가 케이스를 딱 몇개로 지정해두기도 어려울 것 같네욤
일대일로 갈까요???? 마지막 언급(케이스 지정)의 이유로 일대일이 더 나을 것 같습니다ㅏ!

2023-03-04 22:14 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/user/userinfo/UserSupplement.java
> +public class UserSupplement {
standard로 반영완!

2023-03-04 22:37 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/mealinfo/MealNutritionFacts.java
> +  private double cholesterol;
오호 반영완!

2023-03-04 22:37 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/standard/DailyIntakeStandard.java
> +  private double cholesterol;
반영완! totalCalories도 중복되어서 같이 묶었습니다ㅏ

2023-03-04 22:40 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/disease/Disease.java
> +  private List<UserDisease> userDiseaseList = new ArrayList<>();
이거는 사실 무지성 참조하다보니 그렇게 되었는데 연관관계를 단방향으로 해야하는지 양방향으로 해야하는지 제가 고민 좀 해보면 될 것 같아요!!

2023-03-04 23:39 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/disease/Disease.java
> +  private List<UserDisease> userDiseaseList = new ArrayList<>();
맞아  전혀 알필요가 없습니다 왜냐면 질병기준으로 유저의 정보를 모을 일이 딱히 없기 때문
혹여나 같은 질병을 가진 사람들의 식단 정보를 모은다면 모를까ㅏ 
일단 삭제하겠읍니당

2023-03-04 23:53 UTC, anso33 commented
@kyY00n 반영완!

2023-03-05 07:53 UTC, kyY00n commented
언니가 말한 흐름 완벽히 이해했어! 사실 별생각 없이 물어본 거였는데 나도 이제 안심하고 일대일로 가는거 찬성~
브랜치 관리는 ... 음 .. 우리가 계속 운영할 게 아니니까 main에 해도 될거같아!! 나는 상관 없으니까 언니가 도입하고 싶은 방법있으면 적용하고 알려줘~

2023-03-05 07:56 UTC, kyY00n approved these changes
굳굳  어프루브 할게요!!!

2023-03-05 07:56 UTC, kyY00n commented on README.md
> +
최고다 ><

2023-03-05 08:49 UTC, merged

2023-03-11 12:39 UTC, ayoung0073 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime testTime;
testTime이 혈당 체크한 타임인가용???
혈당은 아무때나 체크가능한 거죠? 
프론트엔드에서 보여줄 오늘의 혈당은 어떻게 보여줄지 얘기해보면 좋겠슴다

2023-03-11 12:42 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime testTime;
지금도 이야기 가능욥 
혈당은 아무때나 체크 가능해요 근데 그럼 굳이 datetime이 아니고 date로 둬도 됬을듯염

2023-03-11 13:05 UTC, ayoung0073 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime testTime;
아무때나 체크 가능하묜 datetime으로 두면 될듯!!
오늘의 혈당은 그럼 그날 가장 마지막으로 등록한 혈당으로 하면 어떨까

2023-03-11 13:07 UTC, anso33 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime testTime;
좋아여 그럼 이거 좀 더 엔티티별로 좀 더 자세한 규칙 적은 페이지 노션에 만들어둘게ㅔㅔ

2023-03-11 13:34 UTC, ayoung0073 commented on todayit/src/main/java/com/juju/todayit/domain/daily/DailyBloodSugar.java
> +  private LocalDateTime testTime;
넵!